[package]
name = "burn_after_reading"
version = "0.0.1"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "testnet" }

[addresses]
burn_after_reading = "0x0"